#pragma once

#define AXON_SUCCESS 0
#define AXON_FAILURE 1
#define AXON_NOT_INITIALIZED 2
#define AXON_OPERATION_REQUIRED 3
#define AXON_INVALID_DIRECTORY 4
#define AXON_NOT_ENOUGH_ARGS 5
#define AXON_INVALID_ARG_TYPE 6
#define AXON_CONFIG_MISSING 10
#define AXON_UNKNOWN_COMMAND 12
#define AXON_SEQ_BEGIN_TRANSACTION_FAILED 13
#define AXON_SEQ_INVALID_FILE 13
#define AXON_SEQ_END_TRANSACTION_FAILED 14
#define AXON_REALLOC_FAILURE 100